### ISSUE TITLE
Appears to be missing an include folder

### ISSUE THREAD

**Issue by ethanrublee** [mkrainin/ecto_corrector#1]
Can't find these files:

``` c++
#include <pose_corrector/model/rigidObjectModel.h>
#include <pose_corrector/utils.h>
```

**Comment by mkrainin** [comment]
installing the pose_corrector package (located here: https://code.ros.org/svn/wg-ros-pkg/branches/trunk_diamondback/sandbox/pose_corrector) should fix this
